### ISSUE TITLE
Add example

### ISSUE THREAD

**Issue by bin4ryio** [medfreeman/nuxt-netlify-cms-module#30]
Hi @medfreeman. First, thanks for the great module.

I'm currently trying to implement this into a fresh `nuxt-community/starter-template`. When I go to live `/admin` the Login with GitHub button is not redirecting to any link.

I have the following configs:

**netlify-cms/config.yml**
```
backend:
  name: github
  repo: bin4ryio/nuxt-cms

media_folder: "assets/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/posts"
    slug: "{{year}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Cover Image", name: "image", widget: "image", required: false, tagname: ""}
      - {label: "Body", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
```

**nuxt.config.js**
```
...
  modules: [
    ["nuxt-netlify-cms", {
      adminPath: "admin",
      adminTitle: "Content Manager",
      cmsConfig: {
        media_folder: "static/uploads"
      }
    }],
    ["nuxtent"]
  ]
...
```

**nuxtent.config.js**
```
module.exports = {
  content: [
    [
      'posts',
      {
        page: '/posts/_slug',
        permalink: '/:year/:slug',
        generate: ['get', 'getAll']
      }
    ]
}
```

I have read into test directory and try to replicate a working repo, no luck. It'd be great if you can include an example to the repo. Thanks!
