### ISSUE TITLE
ReferenceError: regeneratorRuntime

### ISSUE THREAD

**Issue by LavenderGrey** [medfreeman/nuxt-netlify-cms-module#51]
I'm getting the following error:

 ERROR  build:compile
 ReferenceError: regeneratorRuntime is not defined

I didn't have any problems before installing the module. I'm using "@nuxtjs/axios": "4.5.2",  "nuxt":1.4.0", "nuxtent": "1.4.1"

any suggestions?

**Comment by benjamindedonder** [comment]
I am having the same issue

    "@nuxtjs/axios": "^5.3.1",
    "nuxt": "^1.4.0",
    "nuxt-netlify-cms": "^3.0.0",
    "nuxtent": "^1.4.1",

**Comment by stursby** [comment]
Also getting this issue... same dep versions

```json
"dependencies": {
    "@nuxtjs/axios": "^5.3.1",
    "nuxt": "^1.4.0",
    "nuxt-netlify-cms": "^3.0.0",
    "nuxtent": "^1.4.1"
 }
```

**Comment by huygn** [comment]
I got the same issue, solved by adding `babel-polyfill`

```
yarn add -D babel-polyfill
```

then add `require('babel-polyfill')` at the top of your `nuxt.config.js`

**Comment by LavenderGrey** [comment]
@huygn It works now thank you. I had tried to before to add babel-polyfill in my build and that didn't work. At top is perfect :smiley:

**Comment by medfreeman** [comment]
I just added `transform-runtime` babel plugin, so webpack properly transforms async functions in the resulting build.
You should not need to require `babel-polyfill` anymore.
Thanks for the report !

**Comment by medfreeman** [comment]
I'll cut a release in a moment, when i have closed a remaining issue.

**Comment by benjamindedonder** [comment]
Updated to netlify-cms 1.7.0 and nuxt-netlify-cms 3.0.1 and when I navigate to http://localhost:3000/admin I get:
```
Error loading the CMS configuration

The config.yml file could not be loaded or failed to parse properly.

Error message: YAMLException: end of the stream or a document separator is expected at line 15, column 14: line-height: 1.15; /* 1 */ ^

Check your console for details.
```

**Comment by benjamindedonder** [comment]
```yaml
backend:
  name: git-gateway
  repo: benjamindedonder/hetvoedselbos.be
  branch: dev

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

display_url: https://dev.hetvoedselbos.be

collections:
  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "content/events"
    create: true
    slug: "{{date}}_{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
```
