### ISSUE TITLE
Error when navigating to /admin

### ISSUE THREAD

**Issue by cringer** [medfreeman/nuxt-netlify-cms-module#72]
Receiving the following error when navigating to the /admin url (which redirects to /admin#/)

```
Error loading the CMS configuration

The config.yml file could not be loaded or failed to parse properly.

Error message: Error: Error in configuration file: A `backend` wasn't found. Check your config.yml file.

Check your console for details.
```

Might just be user error as the documentation is not very clear on loading this.

My website is currently just a basic Nuxt starter template with the nuxt-netlify-cms-module loaded.  The documentation talks about the `Netlify CMS config module folder` but then further in the blurb states `If you don't use any of the following two features, there's no need to create this folder.`  Creating the folder or not doesn't seem to do anything.

**Comment by cjcrawford** [comment]
Check out the **example** directory in the repo and have a look at the config.
```
netlify-cms/config.yml
```

```yaml
backend:
  name: github # github | gitlab | bitbucket
  repo: cringer/netlify-nuxt # username/repository
...
```
